# This is a basic workflow to help you get started with Actions
# Many vars start with RUNNER_ and ITHUB_.

name: GitHub Actions - Use Artifacts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-1:
    name: "Job - Upload artifact"
    runs-on: ubuntu-latest
    steps:
      - name: "Step - Print artifact in a file"
        run: echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor turpis nec pretium vestibulum. Nulla facilisi. Praesent rhoncus ornare vestibulum." > my-artifact.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: my-artifact.txt

  build-2:
    name: "Job - Download artifact"
    runs-on: ubuntu-latest
    needs: build-1
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: "Step - Print artifact from a file"
        run: cat my-artifact.txt
