# This is a basic workflow to help you get started with Actions

name: GitHub Actions - Create Variables

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  defaultVariable: "default"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-1-a:
    name: "Job 1A - Build"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Step 1 - Hello World"
        run: |
          echo "Hello world, I'm running on ubuntu"
          sleep 10

      - name: "Step 2 - Print default variable"
        run: |
          echo "Variable Default: ${{ env.defaultVariable }}"

      - name: "Step 3 - Replace default variable"
        run: |
          echo "defaultVariable=newDefault" >> $GITHUB_ENV
        # Cannot use the new variable in the same step
        # echo "Variable Default: ${{ env.defaultVariable }}"

      - name: "Step 4 - Print new default variable"
        run: |
          echo "Variable Default: ${{ env.defaultVariable }}"

      - name: "Step 5 - Create new variable"
        run: |
          echo "newVariable=new" >> $GITHUB_ENV
        # Cannot use the new variable in the same step
        # echo "New Variable: ${{ env.newVariable }}"

      - name: "Step 6 - Print new variable"
        run: |
          echo "New Variable: ${{ env.newVariable }}"

  build-2:
    name: "Job 2 - Build"
    needs: build-1-a
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1 - Hello World"
        run: echo "Hello world, I'm running on ubuntu"

      - name: "Step 2 - Print default variable"
        run: |
          echo "Variable Default: ${{ env.defaultVariable }}"

      - name: "Step 3 - Print new variable"
        run: |
          echo "New Variable: ${{ env.newVariable }}"

  build-1-b:
    name: "Job 1B - Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1 - Hello World"
        run: |
          echo "Hello world, I'm running on ubuntu"
          sleep 1

      - name: "Step 2 - Print default variable"
        run: |
          echo "Variable Default: ${{ env.defaultVariable }}"

      - name: "Step 3 - Print new variable"
        run: |
          echo "New Variable: ${{ env.newVariable }}"
