# This is a basic workflow to help you get started with Actions
# Many vars start with RUNNER_ and ITHUB_.

name: GitHub Actions - Use GitHub Artifacts

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-1:
    name: "Job - Upload artifact"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Step - Print artifact in a file"
        run: echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec porttitor turpis nec pretium vestibulum. Nulla facilisi. Praesent rhoncus ornare vestibulum." > my-artifact.txt

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my-artifact.txt

    name: "Job - Download artifact"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        - uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: "Step - Print artifact from a file"
        run: cat my-artifact.txt
