# This is a basic workflow to help you get started with Actions

name: GitHub Actions - Use Custom Variables

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  envWorkflowVariable: "I'm an environment variable at the workflow level"
  overridenVariable: "workflow"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-1:
    name: "Job - Build 1"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      envJobVariable: "I'm an environment variable at the job level"
      overridenVariable: "job"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Step - Run a ubuntu script 1"
        run: echo "I'm running on ubuntu 1"

      - name: "Step - Run script with all variables"
        env:
          envStepVariable: "I'm an environment variable at the step level"
          overridenVariable: "step"

        run: |
          echo "Variable Workflow: ${{ env.envWorkflowVariable }}"
          echo "Variable Job: ${{ env.envJobVariable }}"
          echo "Variable Step: ${{ env.envStepVariable }}"
          echo "Variable Overriden: ${{ env.overridenVariable }}"

      - name: "Step - Run script with step variables missing"
        run: |
          echo "Variable Workflow: ${{ env.envWorkflowVariable }}"
          echo "Variable Job: ${{ env.envJobVariable }}"
          echo "Variable Step: ${{ env.envStepVariable }}"
          echo "Variable Overriden: ${{ env.overridenVariable }}"


  build-2:
    name: "Job - Build 2"
    needs: build-1
    runs-on: ubuntu-latest
    steps:
      - name: "Step - Run a ubuntu script 2"
        run: echo "I'm running on ubuntu 2"

      - name: "Step - Run script with step and job variables missing"
        run: |
          echo "Variable Workflow: ${{ env.envWorkflowVariable }}"
          echo "Variable Job: ${{ env.envJobVariable }}"
          echo "Variable Step: ${{ env.envStepVariable }}"
          echo "Variable Overriden: ${{ env.overridenVariable }}"

