# This is a basic workflow to help you get started with Actions
# Many vars start with RUNNER_ and GITHUB_.

name: GitHub Actions - Use GitHub Variables

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu-environment-variables:
    name: "Job - Ubuntu Environment Variables"
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1 - Display GitHub environment variables"
        run: env

      - name: "Step 2 - Display common variables"
        run: |
          echo "GITHUB_ACTION: ${{ github.action }}"
          echo "GITHUB_ENV: ${{ github.action }}"
          echo "GITHUB_API_URL: ${{ github.api_url }}"
          echo "GITHUB_SERVER_URL: ${{ github.server_url }}"
          echo "GITHUB_JOB: ${{ github.job }}"
          echo "GITHUB_PATH: ${{ github.path }}"
          echo "GITHUB_REPOSITORY: ${{ github.repository }}"
          echo "GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}"
          echo "GITHUB_RUN_ID: ${{ github.run_id }}"
          echo "GITHUB_RUN_NUMBER: ${{ github.run_number }}"
          echo "GITHUB_WORKFLOW: ${{ github.workflow }}"
          echo "RUNNER_OS: ${{ runner.os }}"
          echo "RUNNER_NAME: ${{ runner.name }}"


  macos-environment-variables:
    name: "Job - MacOS Environment Variables"
    runs-on: macos-latest
    steps:
      - name: "Step 1 - Display GitHub environment variables"
        run: env

  windows-environment-variables:
    name: "Job - Windows Environment Variables"
    runs-on: windows-latest
    steps:
      - name: "Step 1 - Display GitHub environment variables"
        run: env
