# This is a basic workflow to help you get started with Actions
# Many vars start with RUNNER_ and ITHUB_.

name: GitHub Actions - Use GitHub Secrets

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-1:
    name: "Job - Build 1"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Step - Print Secrets"
        run: |
          echo "MY_SECRET: ${{ secrets.MY_SECRET }}"
          echo "MY_NON_SECRET: ${{ secrets.MY_NON_SECRET }}"


      - name: "Step - Save Secret to Environment Variables"
        env:
          MY_SAVED_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "MY_SAVED_SECRET: ${{ env.MY_SAVED_SECRET }}"

