# This is a basic workflow to help you get started with Actions
# Many vars start with RUNNER_ and ITHUB_.

name: GitHub Actions - Use Secrets

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-1:
    name: "Job - Build 1"
    runs-on: ubuntu-latest
    steps:
      - name: "Step - Print Secrets"
        run: |
          echo "MY_SECRET: ${{ secrets.MY_SECRET }}"
          echo "MY_NON_SECRET: ${{ secrets.MY_NON_SECRET }}"


      - name: "Step - Save Secret to Environment Variables"
        env:
          MY_SAVED_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "MY_SAVED_SECRET: ${{ env.MY_SAVED_SECRET }}"
